import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Customer, IndividualCustomer } from '@/types/customer';
import { format } from 'date-fns';

export interface PDFFieldOption {
  id: string;
  label: string;
  key: string;
  formatter?: (customer: Customer | IndividualCustomer) => string;
}

export interface PDFGenerationOptions {
  fields: PDFFieldOption[];
  customers: (Customer | IndividualCustomer)[];
  gymName: string;
  userName: string;
  reportDate: Date;
}

/**
 * Available fields for PDF generation
 */
export const AVAILABLE_PDF_FIELDS: PDFFieldOption[] = [
  {
    id: 'clientId',
    label: 'Client ID',
    key: 'clientId',
    formatter: (customer) => ('clientId' in customer && customer.clientId) ? customer.clientId : '-',
  },
  {
    id: 'name',
    label: 'Name',
    key: 'name',
    formatter: (customer) => {
      if ('firstName' in customer && customer.firstName) {
        return `${customer.firstName} ${customer.lastName || ''}`.trim();
      }
      return ('name' in customer && customer.name) ? customer.name : '-';
    },
  },
  {
    id: 'email',
    label: 'Email',
    key: 'email',
    formatter: (customer) => customer.email || '-',
  },
  {
    id: 'mobileNumber',
    label: 'Phone/Mobile',
    key: 'mobileNumber',
    formatter: (customer) => customer.mobileNumber || '-',
  },
  {
    id: 'nic',
    label: 'NIC',
    key: 'nic',
    formatter: (customer) => ('nic' in customer && customer.nic) ? customer.nic : '-',
  },
  {
    id: 'packageName',
    label: 'Package Name',
    key: 'package_name',
    formatter: (customer) => customer.package_name || '-',
  },
  {
    id: 'status',
    label: 'Status',
    key: 'isActive',
    formatter: (customer) => customer.isActive ? 'Active' : 'Inactive',
  },
  {
    id: 'paymentStatus',
    label: 'Payment Status',
    key: 'isPaid',
    formatter: (customer) => customer.isPaid ? 'Paid' : 'Unpaid',
  },
  {
    id: 'createdAt',
    label: 'Created Date',
    key: 'createdAt',
    formatter: (customer) => {
      if (!customer.createdAt) return '-';
      try {
        return format(new Date(customer.createdAt), 'MMM dd, yyyy');
      } catch {
        return customer.createdAt;
      }
    },
  },
  {
    id: 'reference',
    label: 'Reference',
    key: 'reference',
    formatter: (customer) => ('reference' in customer && customer.reference) ? customer.reference : '-',
  },
  {
    id: 'address',
    label: 'Address',
    key: 'address',
    formatter: (customer) => {
      if ('addressLine1' in customer) {
        const line1 = customer.addressLine1 || '';
        const line2 = customer.addressLine2 || '';
        return [line1, line2].filter(Boolean).join(', ') || '-';
      }
      return '-';
    },
  },
  {
    id: 'gender',
    label: 'Gender',
    key: 'isMale',
    formatter: (customer) => {
      if ('isMale' in customer) {
        return customer.isMale ? 'Male' : 'Female';
      }
      return '-';
    },
  },
  {
    id: 'dob',
    label: 'Date of Birth',
    key: 'dob',
    formatter: (customer) => {
      if ('dob' in customer && customer.dob) {
        try {
          return format(new Date(customer.dob), 'MMM dd, yyyy');
        } catch {
          return customer.dob;
        }
      }
      return '-';
    },
  },
  {
    id: 'profession',
    label: 'Profession',
    key: 'profession',
    formatter: (customer) => ('profession' in customer && customer.profession) ? customer.profession : '-',
  },
  {
    id: 'whyJoin',
    label: 'Why Join',
    key: 'whyJoin',
    formatter: (customer) => ('whyJoin' in customer && customer.whyJoin) ? customer.whyJoin : '-',
  },
];

/**
 * Generate PDF for customers with selected fields
 */
export function generateCustomersPDF(options: PDFGenerationOptions): void {
  const { fields, customers, gymName, userName, reportDate } = options;

  // Create new PDF document
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  // Set font
  doc.setFont('helvetica');

  // Header Section
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  let yPos = margin;

  // System Name
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('ManZer-Payzhe gym management system', pageWidth / 2, yPos, { align: 'center' });
  yPos += 8;

  // Gym Name
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text(`Gym: ${gymName}`, pageWidth / 2, yPos, { align: 'center' });
  yPos += 6;

  // User Name
  doc.setFontSize(12);
  doc.text(`Generated by: ${userName}`, margin, yPos);
  
  // Report Date
  const dateStr = format(reportDate, 'MMM dd, yyyy HH:mm');
  doc.text(`Report Date: ${dateStr}`, pageWidth - margin, yPos, { align: 'right' });
  yPos += 10;

  // Title
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Customers Report', pageWidth / 2, yPos, { align: 'center' });
  yPos += 8;

  // Prepare table data
  const headers = fields.map(field => field.label);
  const rows = customers.map(customer => 
    fields.map(field => {
      if (field.formatter) {
        return field.formatter(customer);
      }
      // Fallback to direct property access
      const value = (customer as any)[field.key];
      return value !== null && value !== undefined ? String(value) : '-';
    })
  );

  // Generate table
  autoTable(doc, {
    head: [headers],
    body: rows,
    startY: yPos,
    styles: {
      fontSize: 8,
      cellPadding: 2,
      overflow: 'linebreak',
      cellWidth: 'wrap',
    },
    headStyles: {
      fillColor: [66, 139, 202], // Blue color
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 9,
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245],
    },
    margin: { top: yPos, right: margin, bottom: margin, left: margin },
    didDrawPage: (data) => {
      // Add page numbers
      const pageCount = doc.getNumberOfPages();
      doc.setFontSize(10);
      doc.text(
        `Page ${data.pageNumber} of ${pageCount}`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      );
    },
  });

  // Save PDF
  const fileName = `customers-report-${format(reportDate, 'yyyy-MM-dd-HHmm')}.pdf`;
  doc.save(fileName);
}


